void main() {
String suspect = "Michael scott";

  switch(suspect){
    case "Michael scott":
      print("Michael scott is the culprit");
      break;
      
    case "Janet smith":
      print("Janet simth is the culprit");
      break;
    case "Bob johnson":
      print("Bob johnson is the culprit ");
      break;
    
    default:
      print("Please provide a suspect");
      
  }
}
//igualmente todos sabiamos que michael scott era culpable .
